lib/metgauge_web/router.ex
defmodule MetgaugeWeb.Router do
  use MetgaugeWeb, :router

  require Logger

  import MetgaugeWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
    plug MetgaugeWeb.Plugs.GetLocale
  end

  pipeline :app do
    plug :browser
    plug :put_root_layout, {MetgaugeWeb.LayoutView, :landing}
  end

  pipeline :registration do
    plug :app
    plug :put_root_layout, {MetgaugeWeb.LayoutView, :landing}
    plug :put_layout_class, "registration"
  end

  pipeline :landing do
    plug :app
    plug :put_layout_class, "landing"
  end

  pipeline :password_reset do
    plug :app
    plug :put_layout_class, "password-reset"
  end

  pipeline :onboard do
    plug :app
    plug :put_layout_class, "onboard"
  end

  pipeline :admin do
    plug :browser
    plug MetgaugeWeb.Plugs.AdminAccess
    plug :put_root_layout, {MetgaugeWeb.LayoutView, :admin}
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_secure_browser_headers
    plug :fetch_current_user
    plug MetgaugeWeb.Plugs.GetLocale
    plug MetgaugeWeb.Plugs.AdminAccess
  end
  
  scope "/", MetgaugeWeb, as: :user do
    pipe_through [:browser]
    get "/auth/resend_confirmation", Users.ConfirmationController, :resend_confirmation
    get "/auth/confirm/:token", Users.ConfirmationController, :edit
    post "/auth/confirm/:token", Users.ConfirmationController, :update
    get "/get_notifications", Users.SettingsController, :get_notifications
    get "/get_notifications_lazy", Users.SettingsController, :get_notifications_lazy
  end

  scope "/", MetgaugeWeb do
    pipe_through [:landing]
    get "/", PageController, :index
    get "/privacy-policy", PageController, :privacy_policy
    get "/terms-of-use", PageController, :terms_of_use
  end

  scope "/admin", MetgaugeWeb do
    pipe_through [:admin, :require_authenticated_user]
    get "/", AdminController, :index
    get "/user_notifications", AdminController, :user_notifications
    get "/user_notifications_lazy", AdminController, :user_notifications_lazy
    get "/sudo_login/:user_id", Users.SessionController, :sudo_login
  end

  scope "/admin", MetgaugeWeb, as: :admin do
    # TODO: Check they're a seller?
    pipe_through [:api, :require_authenticated_user]
  end

  scope "/admin", MetgaugeWeb, as: :admin do
    # TODO: Check they're a seller?
    pipe_through [:admin, :require_authenticated_user]
    get "/report_widget", AdminController, :report_widget
    get "/profile/edit", ProfileController, :edit
    put "/profile", ProfileController, :update
    resources "/clients", ClientController
    post "/clients/:id", ClientController, :update
    get "/users/filter", UserController, :filter
    delete "/users/:id/toggle_deactivate", UserController, :toggle_deactivate
    resources "/users", UserController
    post "/users/:id", UserController, :update
    post "/users/:id/confirm", UserController, :confirm
  end

  scope "/auth", MetgaugeWeb.Users, as: :user do
    pipe_through [:registration, :redirect_if_user_is_authenticated]

    get "/register", RegistrationController, :new
    get "/register/:client_slug", RegistrationController, :new
    post "/register", RegistrationController, :create
    get "/sign_in", SessionController, :new
    post "/sign_in", SessionController, :create
  end

  scope "/auth", MetgaugeWeb.Users, as: :user do
    pipe_through [:browser, :require_authenticated_user]

    get "/settings", SettingsController, :edit
    put "/settings", SettingsController, :update
    get "/settings/confirm_email/:token", SettingsController, :confirm_email
  end

  scope "/oauth", MetgaugeWeb.Users, as: :user do
    pipe_through [:browser, :registration]

    get "/:provider", OauthController, :request
    get "/:provider/callback", OauthController, :callback
  end

  scope "/auth", MetgaugeWeb.Users, as: :user do
    pipe_through [:password_reset, :redirect_if_user_is_authenticated]

    get "/reset_password", ResetPasswordController, :new
    post "/reset_password", ResetPasswordController, :create
    get "/reset_prompt", ResetPasswordController, :prompt
    get "/reset_password/:token", ResetPasswordController, :edit
    put "/reset_password/:token", ResetPasswordController, :update
  end

  scope "/auth", MetgaugeWeb.Users, as: :user do
    pipe_through [:registration]

    get "/sign_out", SessionController, :delete
    delete "/sign_out", SessionController, :delete

    get "/confirm", ConfirmationController, :new
    post "/confirm", ConfirmationController, :create
    get "/halt", ConfirmationController, :halt
  end

  ## ---------------------------------------------------------
  ## Development stuff
  ## ---------------------------------------------------------

  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: MetgaugeWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  defp put_layout_class(conn, class) do
    conn |> assign(:layout_class, class)
  end
end

lib/metgauge/accounts/profile.ex
defmodule Metgauge.Accounts.Profile do
  use Ecto.Schema
  import Ecto.Changeset

  alias Metgauge.Accounts.{UserNotification}

  schema "profiles" do
    belongs_to :user, Metgauge.Accounts.User
    field :role, :string, default: "manager"
    field :handle, :string, default: ""
    field :first_name, :string, default: ""
    field :last_name, :string, default: ""
    field :about, :string, default: ""
    field :timezone, :string, default: ""
    field :languages, {:array, :string}, default: []
    field :avatar_path, :string
    field :original_avatar_path, :string
    field :cover_path, :string

    has_many :unanswered_user_notifications, UserNotification, foreign_key: :id
    has_many :answered_user_notifications, UserNotification, foreign_key: :id
  end

  def edit_changeset(profile, attrs, _opts \\ []) do
    profile
    |> cast(attrs, [:first_name, :last_name, :avatar_path, :handle, :cover_path, :about, :timezone, :languages, :original_avatar_path, :avatar_path, :cover_path])
    |> validate_required([:first_name, :last_name])
  end

  def add_changeset(profile, attrs, _opts \\ []) do
    profile
    |> cast(attrs, [:first_name, :last_name, :avatar_path, :handle, :cover_path, :about, :timezone, :languages, :original_avatar_path, :avatar_path, :cover_path, :role])
    |> validate_required([:first_name, :last_name])
  end

  def update_changeset(profile, attrs) do
    profile
    |> cast(attrs, [:first_name, :last_name, :avatar_path, :handle, :cover_path, :about, :timezone, :languages, :original_avatar_path, :avatar_path, :cover_path, :role])
    |> validate_required([:first_name, :last_name, :timezone])
    |> validate_length(:about, max: 2600)
    |> validate_inclusion(:role, ["manager", "operator", "admin", "superadmin"])
  end

  def all_languages(), do: (["English", "Spanish", "Chinese", "Japanese"] ++ (Enum.sort(LanguageList.common_languages) -- ["English", "Spanish", "Chinese", "Japanese"]))
  def languages(), do: (["English", "Spanish", "Chinese", "Japanese"] ++ (Enum.sort(LanguageList.common_languages) -- ["English", "Spanish", "Chinese", "Japanese"])) |> Enum.map(&(%{key: &1, value: Gettext.dgettext(MetgaugeWeb.Gettext, "default", &1)}))
end

lib/metgauge/profiles.ex
defmodule Metgauge.Profiles do
  require Logger

  import Ecto.Query, warn: false

  alias Metgauge.Repo

  alias Metgauge.Accounts.{Profile, User}
  import MetgaugeWeb.Gettext

  def get_profile_by_handle(handle) when is_binary(handle) do
    Repo.get_by(Profile, handle: handle) |> Repo.preload([:user])
  end

  def add_profile(attrs) do
    %Profile{}
    |> Profile.add_changeset(attrs)
    |> Repo.insert()
  end

  def update(%Profile{} = profile, attrs \\ %{}) do
    Profile.update_changeset(profile, attrs)
    |> Repo.update()
  end

  def summary_map(nil), do: nil
  def summary_map(profile), do: profile

  def update_profile(profile, params) do
    Ecto.Multi.new()
    |> Ecto.Multi.run(:avatar_path, fn _repo, _changes ->
      case params do
        %{"remove_image" => _} ->
          {:ok, nil}
        %{"avatar_path" => %{path: path, filename: filename}} ->
          try do
            Mogrify.open(path) |> Mogrify.resize_to_limit("300x300") |> Mogrify.quality("90") |> Mogrify.save(in_place: true)
            uuid = UUID.uuid4()
            file_extension = Path.extname(filename)
            new_path = File.cwd! <> "/uploads/" <> uuid <> file_extension
            File.rename(path, new_path)
            {:ok, uuid <> file_extension}
          rescue
            error ->
              IO.inspect(error)
              {:error, gettext("Not able to upload image")}
          end
        _ -> {:ok, profile.avatar_path}
      end
    end)
    |> Ecto.Multi.run(:profile, fn _repo, %{avatar_path:  avatar_path} ->
        interests = Map.get(params, "interests", [])
        params = Map.merge(params, %{"avatar_path" => avatar_path, "interests" => interests})
        changeset = Profile.update_changeset(profile, params)
        Repo.update(changeset)
      end)
    |> Ecto.Multi.run(:user, fn _repo, %{} ->
      user = Repo.get(User, profile.user_id)
      User.update_email_changeset(user, %{"email" => params["email"]})
      |> Repo.update()
    end)
    |> Repo.transaction(timeout: :infinity)
  end
end

lib/metgauge_web/controllers/profile_controller.ex
defmodule MetgaugeWeb.ProfileController do
  use MetgaugeWeb, :controller
  alias Metgauge.Accounts.Profile
  alias Metgauge.Profiles
  alias Metgauge.Helpers.ChangesetHelpers

  def edit(conn, _params) do
    profile = conn.assigns.profile
    attrs = %{email: conn.assigns.current_user.email}
    changeset = Profile.edit_changeset(profile, attrs)
    render(conn, "edit.html", profile: profile, changeset: changeset)
  end

  def update(conn, %{"profile" => params} = _attrs) do
    profile = conn.assigns.profile
    IO.inspect(params)
    with \
      {:ok, %{profile: _profile}} <- Profiles.update_profile(profile, params)
    do
      json(conn, %{status: "OK"})
    else
      {:error, _model, %{field: field} = _error_field, _data} ->
        json(conn, %{status: "ERROR", fields: [%{field: field, message: gettext("Invalid input")}]})
      {:error, model, message, _data} when is_binary(message) ->
        json(conn, %{status: "ERROR", fields: [%{field: model, message: message}]})
      {:error, _model, changeset, _data} ->
        IO.inspect(changeset);
        json(conn, %{status: "ERROR", fields: ChangesetHelpers.changeset_error_to_array(changeset)})
    end
  end
end

lib/metgauge_web/views/profile_view.ex
defmodule MetgaugeWeb.ProfileView do
  use MetgaugeWeb, :view
  import MetgaugeWeb.Helpers.{OptionHelpers}
  alias Metgauge.Accounts.Profile

  def languages() do
    Profile.languages()
    |> Enum.map(fn(l)-> %{key: l, value: l} end)
  end
  
  def profile_cover_photo(conn, profile) do
    if profile.cover_path == "" or profile.cover_path == nil do
      "background: url('#{Routes.static_path(conn, "/assets/images/default_banner_image.png")}')"
    else
      "background: url('#{Routes.static_path(conn, "/uploads/"<>profile.cover_path)}'); background-position: #{profile.cover_position};"
    end
  end

  def profile_image_url(conn, profile) do
    if profile == nil or profile.avatar_path == "" or profile.avatar_path == nil do
      Routes.static_url(conn, "/assets/svg/generic/no_profile_photo.svg")
    else
      Routes.static_path(conn, "/uploads/#{profile.avatar_path}")
    end
  end

  def profile_email_image_url(conn, profile) do
    if profile == nil or profile.avatar_path == "" or profile.avatar_path == nil do
      Routes.static_url(conn, "/assets/images/no_profile.png")
    else
      Routes.static_url(conn, "/uploads/#{profile.avatar_path}")
    end
  end

end

lib/metgauge_web/templates/profile/edit.html.heex
 <div class="profile-form">
   <h2><%= gettext("Profile") %></h2>
    <%= form_for @changeset, Routes.admin_profile_path(@conn, :update), [method: "PUT", multipart: true, name: "profile"], fn f -> %>
    <div class="profile">
      <div class="forms">
        <div class="half-col">
          <div class="full-col">
            <div class="forms-title"><h6><%= gettext("Personal information") %></h6></div>
          </div>
          <div class="full-row">
            <div class="full-col" style="display: flex; flex-direction: row;">
              <div class="avatar">
                <img id="profile-avatar" src={profile_image_url(@conn, @profile)} alt="Profile avatar" class={if @profile == nil or @profile.avatar_path == "" or @profile.avatar_path == nil do "no_profile_img" end}/>
              </div>
              <div href="" class="avatar-edit-btns">
                  <%= file_input f, :avatar_path, style: "display: none" %>
                  <button type="primary" class="primary" id="upload-avatar"><%= gettext("Upload") %></button>
                  <button class="secondary" id="remove-image" style={if @profile == nil or @profile.avatar_path == "" or @profile.avatar_path == nil do "display: none" end}><%= gettext("Remove") %></button>
                  <%= label f, :avatar_path, class: "invalid-feedback" %>
              </div>
            </div>
          </div>
          <div class="full-row">
            <div class="half-col">
                <div class="field-title"><%= gettext("First name") %></div>
                <%= text_input f, :first_name, class: "form-field", placeholder: gettext("First name"), maxlength: "255" %>
                <%= label f, :first_name, class: "invalid-feedback" %>
            </div>
            <div class="half-col">
                <div class="field-title"><%= gettext("Last name") %></div>
                <%= text_input f, :last_name, class: "form-field", placeholder: gettext("Last name"), maxlength: "255" %>
                <%= label f, :last_name, class: "invalid-feedback" %>
            </div>
          </div>
          <div class="full-row">
            <div class="full-col">
                <div class="field-title"><%= gettext("Email") %></div>
                <%= text_input f, :email, class: "form-field", placeholder: gettext("Email"), maxlength: "255" %>
                <%= label f, :email, class: "invalid-feedback" %>
            </div>
          </div>
          <div class="full-row">
            <div class="full-col">
                <div class="field-title description-title">
                  <%= gettext("About you") %>
                </div>
                <%= textarea f, :about, class: "form-field", placeholder: gettext("About you"), maxlength: "2600", style: "height: 132px" %>
                <div class="form-field-bottom">
                  <%= gettext("Maximum 2,600 characters") %>
                </div>
                <%= label f, :about, class: "invalid-feedback" %>
            </div>
          </div>
        </div>
        <div class="half-col">
          <br/>
          <br/>
          <div class="full-row">
            <div class="full-col">
              <div class="field-title"><%= gettext("Languages Spoken") %></div>
              <select name="profile[languages][]" placeholder={gettext("Choose languages")} multiple="multiple" id="profile_languages">
                <%= for language <- Metgauge.Accounts.Profile.languages() do %>
                  <%= if Enum.member?(@profile.languages, language.key) do %>
                    <option selected="selected" value={ language.key }><%= language.value %></option>
                  <% else %>
                    <option value={ language.key }><%= language.value %></option>
                  <% end %>
                <% end %>
              </select>
              <div class="form-field-bottom hidden">
                <%= gettext("Only visible to yourself") %>
              </div>
              <%= label f, :languages, class: "invalid-feedback" %>
            </div>
          </div>
          <div class="full-row">
            <div class="full-col">
              <div class="field-title"><%= gettext("Time Zone") %></div>
              <select name="profile[timezone]" id="profile_timezone" placeholder={gettext "Choose your timezone"}>
                <option></option>
                <%= for timezone <- timezone_options() do %>
                  <%= if @profile.timezone == timezone.key do %>
                    <option selected="selected" value={ timezone.key }><%= timezone.value %></option>
                  <% else %>
                    <option value={ timezone.key }><%= timezone.value %></option>
                  <% end %>
                <% end %>
              </select>
              <%= label f, :timezone, class: "invalid-feedback" %>
            </div>
          </div>
        </div>
      </div>
      <div class="update-profile-btns">
      <button type="button" onclick={"location.href='" <> Routes.admin_path(@conn, :index) <> "'"} class="tertiary" id="cancel-edit" ><%= gettext("Cancel") %></button>
          <button class="primary" type="button" id="update-profile-btn">
            <%= gettext "Save" %>
            <div class="w-6 h-6 animate-spin loading">
              <svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 48 48" fill="none">
                <path d="M42 24c0 9.941-8.059 18-18 18S6 33.941 6 24 14.059 6 24 6" strokewidth="14" stroke="white">
                </path>
              </svg>
          </div>
        </button>
    </div>
    </div>
<% end %>
  </div>

<style>
  .invalid-feedback, .loading{
    display: none;
  }
  .select2-dropdown.select2-dropdown--below{
    display: block !important;
  }
  .select2-dropdown{
    border: 1px solid lightgray !important;
  }
</style>
<script defer type="text/javascript" src={Routes.static_path(@conn, "/assets/js/profile.js")}></script>
<script defer type="text/javascript" src={Routes.static_path(@conn, "/assets/js/draggable-background.js")}></script>

<script>
  window.profile_languages_placeholder = "<%= gettext "Tell us about your languages" %>";
  $(document).ready(function(){
    $(".handle-txt").html($(".handle-input").val());

    $(".handle-input").on('keydown keyup', function(){
      $(".handle-txt").html($(this).val());
    });


    $('#profile_cover_path').change(function(){
      $(".remove_image_input").remove();
      const file = this.files[0];
      console.log(file);
      if (file){
        let reader = new FileReader();
        reader.onload = function(event){
          $('#profile-cover').attr('src', event.target.result);
          $(".cover").css("background", "url('"+event.target.result+"')");
          $('.cover').backgroundDraggable();
        }
        reader.readAsDataURL(file);

      }
    });
    $('.cover').backgroundDraggable();

    $(".autopopulate_bio").click(function(){
      var social_media_links = []
      $.each(["facebook", "instagram", "linkedin", "youtube", "twitter"], function(id, social_media){
        if($("#profile_"+social_media).val() != ""){
          social_media_links.push($("#profile_"+social_media).val());
        }
      });
      if($("#profile_first_name").val() != "" && $("#profile_last_name").val() != "" && social_media_links.length > 0){
        $(".loading-btn").show();
        $(".autopopulate_bio").attr("disabled", "disabled");
        $.ajax({
          method: "POST",
          url: "/admin/profile/autogenerate_bio",
          data: {"name": $("#profile_first_name").val()+ " " + $("#profile_last_name").val(), "social_links": social_media_links, language: $("[name='profile[language]']").val()},
          headers: { 'x-csrf-token': window.csrfToken },
          dataType: "json",
          success: function(response){
            if(response.status){
              $("#profile_about").val(response.text.trim());
            }
            $(".loading-btn").hide();
            $(".autopopulate_bio").removeAttr("disabled");
          } 
        });
      }
      else{
        alert("<%= gettext "You need to provide name and at least one SNS link to generate." %>");
      }
    });
  });
</script>