lib/metgauge_web/router.ex
defmodule MetgaugeWeb.Router do
  use MetgaugeWeb, :router

  require Logger

  import MetgaugeWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
    plug MetgaugeWeb.Plugs.GetLocale
  end

  pipeline :app do
    plug :browser
    plug :put_root_layout, {MetgaugeWeb.LayoutView, :landing}
  end

  pipeline :registration do
    plug :app
    plug :put_root_layout, {MetgaugeWeb.LayoutView, :landing}
    plug :put_layout_class, "registration"
  end

  pipeline :landing do
    plug :app
    plug :put_layout_class, "landing"
  end

  pipeline :password_reset do
    plug :app
    plug :put_layout_class, "password-reset"
  end

  pipeline :onboard do
    plug :app
    plug :put_layout_class, "onboard"
  end

  pipeline :admin do
    plug :browser
    plug MetgaugeWeb.Plugs.AdminAccess
    plug :put_root_layout, {MetgaugeWeb.LayoutView, :admin}
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_secure_browser_headers
    plug :fetch_current_user
    plug MetgaugeWeb.Plugs.GetLocale
    plug MetgaugeWeb.Plugs.AdminAccess
  end
  
  scope "/", MetgaugeWeb, as: :user do
    pipe_through [:browser]
    get "/auth/resend_confirmation", Users.ConfirmationController, :resend_confirmation
    get "/auth/confirm/:token", Users.ConfirmationController, :edit
    post "/auth/confirm/:token", Users.ConfirmationController, :update
    get "/get_notifications", Users.SettingsController, :get_notifications
    get "/get_notifications_lazy", Users.SettingsController, :get_notifications_lazy
  end

  scope "/", MetgaugeWeb do
    pipe_through [:landing]
    get "/", PageController, :index
    get "/privacy-policy", PageController, :privacy_policy
    get "/terms-of-use", PageController, :terms_of_use
  end

  scope "/admin", MetgaugeWeb do
    pipe_through [:admin, :require_authenticated_user]
    get "/", AdminController, :index
    get "/user_notifications", AdminController, :user_notifications
    get "/user_notifications_lazy", AdminController, :user_notifications_lazy
    get "/sudo_login/:user_id", Users.SessionController, :sudo_login
  end

  scope "/admin", MetgaugeWeb, as: :admin do
    # TODO: Check they're a seller?
    pipe_through [:api, :require_authenticated_user]
  end

  scope "/admin", MetgaugeWeb, as: :admin do
    # TODO: Check they're a seller?
    pipe_through [:admin, :require_authenticated_user]
    get "/report_widget", AdminController, :report_widget
    get "/profile/edit", ProfileController, :edit
    put "/profile", ProfileController, :update
    resources "/clients", ClientController
    post "/clients/:id", ClientController, :update
    get "/users/filter", UserController, :filter
    delete "/users/:id/toggle_deactivate", UserController, :toggle_deactivate
    resources "/users", UserController
    post "/users/:id", UserController, :update
    post "/users/:id/confirm", UserController, :confirm
  end

  scope "/auth", MetgaugeWeb.Users, as: :user do
    pipe_through [:registration, :redirect_if_user_is_authenticated]

    get "/register", RegistrationController, :new
    get "/register/:client_slug", RegistrationController, :new
    post "/register", RegistrationController, :create
    get "/sign_in", SessionController, :new
    post "/sign_in", SessionController, :create
  end

  scope "/auth", MetgaugeWeb.Users, as: :user do
    pipe_through [:browser, :require_authenticated_user]

    get "/settings", SettingsController, :edit
    put "/settings", SettingsController, :update
    get "/settings/confirm_email/:token", SettingsController, :confirm_email
  end

  scope "/oauth", MetgaugeWeb.Users, as: :user do
    pipe_through [:browser, :registration]

    get "/:provider", OauthController, :request
    get "/:provider/callback", OauthController, :callback
  end

  scope "/auth", MetgaugeWeb.Users, as: :user do
    pipe_through [:password_reset, :redirect_if_user_is_authenticated]

    get "/reset_password", ResetPasswordController, :new
    post "/reset_password", ResetPasswordController, :create
    get "/reset_prompt", ResetPasswordController, :prompt
    get "/reset_password/:token", ResetPasswordController, :edit
    put "/reset_password/:token", ResetPasswordController, :update
  end

  scope "/auth", MetgaugeWeb.Users, as: :user do
    pipe_through [:registration]

    get "/sign_out", SessionController, :delete
    delete "/sign_out", SessionController, :delete

    get "/confirm", ConfirmationController, :new
    post "/confirm", ConfirmationController, :create
    get "/halt", ConfirmationController, :halt
  end

  ## ---------------------------------------------------------
  ## Development stuff
  ## ---------------------------------------------------------

  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: MetgaugeWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  defp put_layout_class(conn, class) do
    conn |> assign(:layout_class, class)
  end
end

lib/metgauge_web/views/layout_view.ex
defmodule MetgaugeWeb.LayoutView do
  require Logger

  alias Plug.Conn

  use MetgaugeWeb, :view

  #alias Metgauge.Profiles

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}

  def locale_link(%Conn{ query_params: params }=conn, locale) do
    query = Conn.Query.encode(Map.merge(params, %{ "lang" => locale, "override" => true }))
    path = Phoenix.Controller.current_path(conn, %{})
    "#{path}?#{query}"
  end

  def html_lang(%{assigns: %{locale: locale}} = _conn) do
    locale
    |> String.replace("_", "-")
  end
  def html_lang(_conn), do: "en"

  def get_endpoint_active_class(conn, path) do
    if conn.request_path == path, do: "active", else: ""
  end
  
  def meta_image_width(_assigns) do
    "400"
  end

  def meta_image_height(_assigns) do
    "400"
  end

  def meta_title(_assigns) do
    "Commercial Works"
  end

  def meta_description(%{conn: %{private: %{:phoenix_template => "hero.html", :phoenix_view => MetgaugeWeb.HeroView}} = conn}) do
    case conn.assigns.hero.about do
      "" -> gettext "Join the global talent pool to trade skills and time"
      about -> about
    end
  end
  def meta_description(_assigns) do
    gettext "Commercial Works provides commercial moving and storage, workplace interors, and logistics services for business nationwide. Contact us to learn more!"
  end

  def meta_type(_assigns) do
    "website"
  end

  def meta_price_tags(_assigns) do
    ""
  end

  def meta_image(%{conn: conn} = _assigns) do
    Routes.static_url(conn, "/assets/images/seo_img.png")
  end
end

lib/metgauge_web/templates/layout/_facebook_sign_issue_modal.html.heex
<div class="modal fade fixed top-0 left-0 hidden w-full h-full outline-none overflow-x-hidden overflow-y-auto"
  id="facebookIssueModal" tabindex="-1" aria-labelledby="facebookIssueModal" aria-hidden="true">
  <div class="modal-dialog relative w-auto pointer-events-none modal-dialog-centered">
    <div
      class="modal-content border-none shadow-lg relative flex flex-col w-full pointer-events-auto bg-white bg-clip-padding rounded-md outline-none text-current">
      <div
        class="modal-header">
        <h5 class="text-base font-semibold leading-5 tracking-normal text-center"><%= gettext("Facebook Sign Up/Sign In Issue") %></h5>
        <button type="button"
          class="btn-close box-content w-4 h-4 p-1 text-black border-none rounded-none opacity-50 focus:shadow-none focus:outline-none focus:opacity-100 hover:text-black hover:opacity-75 hover:no-underline"
          data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div>
          <%= gettext "Facebook Services do not work in the in-app browser. Please use another mobile browser (Chrome, Firefox, Safari, ...) to continue." %>
        </div>
      </div>
      <div
        class="modal-footer">
        <!-- 
          <button class="primary text-white copy-link" data-path="<%= Routes.user_oauth_url(@conn, :request, "facebook")%>"><%= gettext "Copy Link" %></button>
        -->
        <button type="button" class="btn primary" data-bs-dismiss="modal" aria-label="Close"><%= gettext("OK") %></button>
      </div>
    </div>
  </div>
</div>

lib/metgauge_web/templates/layout/_google_sign_issue_modal.html.heex
<div class="modal fade fixed top-0 left-0 hidden w-full h-full outline-none overflow-x-hidden overflow-y-auto"
  id="googleIssueModal" tabindex="-1" aria-labelledby="googleIssueModal" aria-hidden="true">
  <div class="modal-dialog relative w-auto pointer-events-none modal-dialog-centered">
    <div
      class="modal-content border-none shadow-lg relative flex flex-col w-full pointer-events-auto bg-white bg-clip-padding rounded-md outline-none text-current">
      <div
        class="modal-header">
        <h5 class="text-base font-semibold leading-5 tracking-normal text-center"><%= gettext("Google Sign Up/Sign In Issue") %></h5>
        <button type="button"
          class="btn-close box-content w-4 h-4 p-1 text-black border-none rounded-none opacity-50 focus:shadow-none focus:outline-none focus:opacity-100 hover:text-black hover:opacity-75 hover:no-underline"
          data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div>
          <%= gettext "Google Services do not work in the in-app browser. Please use another mobile browser (Chrome, Firefox, Safari, ...) to continue." %>
        </div>
      </div>
      <div
        class="modal-footer">
        <!-- 
          <button class="primary text-white copy-link" data-path="<%= Routes.user_oauth_url(@conn, :request, "google")%>"><%= gettext "Copy Link" %></button>
        -->
        <button type="button" class="btn primary" data-bs-dismiss="modal" aria-label="Close"><%= gettext("OK") %></button>
      </div>
    </div>
  </div>
</div>

lib/metgauge_web/templates/layout/_user_menu.html.heex
<%= if @current_user do %>
<% class = if Enum.count(@profile.unanswered_user_notifications) > 0, do: "show", else: "" %>
<li class="menu-notification show">
  <%= if class != "" do %>
    <span></span>
  <% end %>
  <%= Heroicons.icon("bell", type: "outline", class: "h-5 w-5") %>
  <div class="notification-container header-menu hide">
   <div class="heading">
        <a href="" class="close_notifications">
          <%= Heroicons.icon("x-mark", type: "outline", class: "h-5 w-5") %>
        </a>
        <h5><%= gettext "Notifications" %></h5>
            <a href={Routes.admin_path(MetgaugeWeb.Endpoint, :user_notifications)}>
            <span><%= gettext "All" %></span>
            </a>
      </div>
      <div class="animate-spin loading">
          <%= Heroicons.icon("arrow-path", type: "outline", class: "h-5 w-5") %>
      </div>
     <div class="notification-result">
     </div>
     <div class="animate-spin loading-more">
           <%= Heroicons.icon("arrow-path", type: "outline", class: "h-5 w-5") %>
        </div>
  </div>
  <div class="over"></div>
</li>
<% else %>
  <li class="hidden md:flex flex-row gap-3">
      <%= link(gettext("Sign up"), to: Routes.user_registration_path(@conn, :new), method: :get, class: "btn dark hidden md:inline-block") %>
      <%= link(gettext("Sign in"), to: Routes.user_session_path(@conn, :new), method: :get, class: "btn btn-transparent hidden md:inline-block text-gray-700") %>
  </li>
<% end %>

lib/metgauge_web/templates/layout/_user_notifications.html.heex
<nav class="icon-menu">
  <%= for notification <- @user_notifications do %>
    <% onclick_fn = if Enum.member?(["cancel_booking", "request_slot_response", "demo_video", "chatbot"], notification.type), do: "cancelRedirect('#{notification.link}')", else: "" %>
    <% style = if Enum.member?(["cancel_booking", "request_slot_response", "demo_video", "chatbot"], notification.type), do: "cursor: pointer", else: "" %>
    <% answered_class =  if notification.is_answered == false, do: "unanswered-notification notification-item-wrap", else: "notification-item-wrap"%>
    <div class={answered_class} onclick={onclick_fn} style={style}>
      <div class="date-time">
        <%= MetgaugeWeb.AdminView.format_user_notification_datetime(@conn, notification.inserted_at) %>
      </div>
      <div class="main-content" style="width: 100%">
        <div class="user-avatar">
          <img src={Routes.static_url(MetgaugeWeb.Endpoint, "/assets/images/icon-32x32.ico")} class="notification-img default">
        </div>
        <div class="txt">
          <p class="font-semibold">
            <%
              parameters = 
                cond do
                  notification.parameters == nil -> nil
                  Enum.member?(Map.keys(notification.parameters), "event_date") ->
                    date = 
                      case Timex.parse(notification.parameters["event_date"], "{ISO:Extended}") do
                        {:ok, date} -> MetgaugeWeb.AdminView.email_datetime(date, @conn.assigns.locale)
                        _ -> notification.parameters["event_date"]
                      end
                    Map.put(notification.parameters, "event_date", date)
                  Enum.member?(Map.keys(notification.parameters), "seller_event_date") ->
                    date = 
                      case Timex.parse(notification.parameters["seller_event_date"], "{ISO:Extended}") do
                        {:ok, date} -> MetgaugeWeb.AdminView.email_datetime(date, @conn.assigns.locale)
                        _ -> notification.parameters["seller_event_date"]
                      end
                    Map.put(notification.parameters, "seller_event_date", date)
                  true -> notification.parameters
                end
            %>
            <%= if parameters != nil do
                  try do
                    raw(Gettext.dgettext(MetgaugeWeb.Gettext, "default", notification.content, Keyword.new(parameters, fn {k,v} -> {String.to_existing_atom(k), v} end))) 
                  rescue
                    _ -> raw(notification.content)
                  end
                else
                  raw(notification.content)
                end
            %>
          </p>
        </div>
      </div>
      <div class="btns">    
        <%= if notification.type == "job" do %>
          <a class="btn primary medium" href={notification.link}><%= gettext "View" %></a>
        <% end %>
      </div>
    </div>
    <hr/>
  <% end %>
  <!--<a href={Routes.admin_admin_path(MetgaugeWeb.Endpoint, :user_notifications)} class="todo">View all</a>-->
</nav>

<script>
  $(document).ready(function(){
    $(".download-main-calendar-btn").click(function(){
      $(".download-main-calendar").html($(this).next(".event-calendar-options").html());
    });
  });

  function cancelRedirect(link){
    window.location.href=link;
  }
</script>

lib/metgauge_web/templates/layout/app.html.heex
<div class="validation-message">
  <p class="alert alert-info" role="alert"><%= raw(get_flash(@conn, :info)) %></p>
  <p class="alert alert-danger" role="alert"><%= raw(get_flash(@conn, :error)) %></p>
</div>
<%= @inner_content %>

lib/metgauge_web/templates/layout/email.html.heex
<!DOCTYPE html>
<html class="main-class">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <style>
      .email{
          background: #F0F1F1;
          width: 100%;
          height: 100%;
          display: flex;
          justify-content: center;
          align-items: center;
      }

      .email-wrapper{
          padding: 0;
          margin: 16px;
          background: #fff;
      }

      @media (min-width: 768px){
        .email-wrapper{
          margin-left: 20%;
          margin-right: 20%;
        }
      }

      .email-wrapper header{
          padding: 24px 32px;
      }

      .email-wrapper header > img{
          max-width: 170px;
          height: auto;
      }

      .email-wrapper footer{
          width: 100%;
          text-align: left;
          padding: 16px 32px;
          color: #101828;
          font-size: 14px;
          font-weight: 400;
          line-height: 22px;
          letter-spacing: 0px;
      }

      .email-main-body{
          padding: 32px;
          text-align: left;
      }
      .email-main-body p{
          font-size: 16px;
          font-weight: 400;
          line-height: 22px;
          letter-spacing: 0px;
          text-align: left;
          color: #1D2939;
      }

      .email-main-body .title h2, .email-main-body .title{
          margin: 0;
          padding: 0;
          font-size: 32px;
          font-weight: 700;
          line-height: 40px;
          letter-spacing: 0em;
          color: #101828;
      }
      .email-main-body .title{
          padding-bottom: 12px;
      }
      .email-main-body a{
          font-size: 16px;
          font-weight: 700;
          line-height: 22px;
          letter-spacing: 0px;
          text-align: left;
          color: #101828;
      }

      .email-main-body b{
          color: #101828;
      }

      .email-main-body .hero-wrapper{
          padding-left: 0!important;
          padding-right: 0!important;
          padding-top: 0!important;
          padding-bottom: 0!important;
          height: 100%!important;
      }

      .email-main-body .booking-flow-main.confirmation{
          padding: 0!important;
          height: 100%!important;
          box-shadow: none!important;
      }

      .email-main-body .booking-flow-main.confirmation .main-content li{
          padding: 0!important;
      }

      .email-main-body .booking-flow-main{
          border-radius: 0!important;
      }

      .email-main-body .booking-flow-main h2{
          font-size: 24px!important;
          line-height: 32px!important;
      }

      .email-main-body .mailtolink{
        font-size: 16px;
        font-weight: 400;
        line-height: 22px;
        letter-spacing: 0px;
        text-align: left;
        text-decoration: underline;
      }
      .email-main-body ul, .email-main-body ol{
          padding: 16px 0;
      }
      a{
        text-decoration: inherit;
      }

      button, .btn {
        display: inline-flex;
        flex-direction: row;
        align-items: center;
        gap: 0.75rem;
        font-family: Gantari;
        justify-content: center;
        background-color: rgb(242, 244, 247);
        text-align: center;
        font-weight: 600;
        cursor: pointer;
        white-space: nowrap;
        padding: 10px 16px;
        border-radius: 8px;
      }
      button.dark, .btn.dark, button.primary, .btn.primary {
        background-color: #004e7d;
        color: rgb(255, 255, 255);
        padding: 18px;
      }
      body{
        font-family: 'Gantari', sans-serif;
      }
      a.content{
          font-weight: normal !important;
      }

      .event_slot_dates{
          font-size: small !important;
          padding: 5px 8px !important;
      }
      .event_type_div{
          display: flex;
      }
      .border_bottom{
          border: 0px;
          border-bottom-width: 1px;
          border-style: solid;
          border-color: #d0d5dd;
          padding-bottom: 5px;
      }

      .main_sellers div{
          margin-right: 20px;
      }

      .seller_div{
        margin-bottom: 20px;
      }

      .time-seller-item {
            display: flex;
            align-items: top;
            justify-content: flex-start;
            gap: 1rem;
        }

        .time-seller-item .img {
            height: 50px;
            min-width: 50px;
            min-height: 50px;
            max-height: 50px;
            overflow: hidden;
            background-color: rgb(208, 213, 221);
            border-radius: 12px;
            margin-right: 10px;
        }

        .time-seller-item h4{
            margin: 0;
        }

        .time-seller-item .img img {
            height: 100%;
            width: 100%;
            object-fit: cover;
            object-position: top;
        }

    .event_type_div.card {
        left: 0px;
        top: 0px;
        display: block;
        margin-top: 4px;
        margin-bottom: 8px;
        border-width: 8px;
        background-color: rgb(255, 255, 255);
        padding: 12px;
        border-radius: 12px;
        border: 2px solid rgb(228, 231, 236);

    }

    .event_type_div.card .img {
      background-color: #F7F7F7;
      border-radius: 8px;
    }

    .event_type_div.card .img {
        width: 100%;
        overflow: hidden;
        height: 156px;
        text-align: center;
    }

    .event_type_div.card .img a img {
        height: 100%;
        width: auto;
        border-radius: 8px;
        margin: 0 auto;
        -o-object-fit: cover;
        object-fit: cover;
    }

    .event_type_div.card h3, .event_type_div.card h3 a {
        padding-top: 0.25rem;
        padding-bottom: 0.25rem;
        text-align: left;
        font-size: 16px;
        line-height: 10px;
        color: rgb(16, 24, 40);
    }

    .event_type_div.card .top {
        display: block;
        padding-top: 12px;
        font-size: 12px;
        font-weight: 700;
        line-height: 16px;
        color: rgb(102, 112, 133);
    }

    .dot{
        margin: 2px;
        background-color: rgb(208, 213, 221);
        height: 4px;
        width: 4px;
        border-radius: 50%;
        display: inline-block;
    }
    .event-slots a{
         font-family: 'Inter', sans-serif;
    }
    .event-slots{
        display: flex;
        gap: 15px;
        flex-wrap: wrap;
    }

    .main_sellers div{
        margin-right: 0
    }

     @media (max-width: 768px){
        .event-slots {
            display: block;
        }

        .email-main-body .event-slots a{
            width: calc(100% - 12px);
            margin-top: 5px;
            font-size: large !important;
            text-align: center !important;
            display: inline-block !important;
        }
      }
    .original:before{
        content: "("
    }

    .original:after{
        content: ")"
    }

    .original{
        font-style: italic;
    }
    
    .chatbot-response .message{
        display: flex;
        flex-direction: column-reverse;
    }
  </style>
  </head>
  <body>
    <div class="email">
      <div class="email-wrapper" style="background: white;">
          <header style="background: white;">
              <img class="logo" src={Routes.static_url(@conn, "/assets/images/logo.png")}/>
          </header>
          <div class="email-main-body">
              <%= @inner_content %>
          </div>
          <footer>
              <%= gettext("All rights reserved. &copy; %{year} MetGauge", year: Timex.now().year) |> raw() %>
          </footer>
      </div>
    </div>
  </body>
</html>

lib/metgauge_web/templates/layout/live.html.heex
<%= @inner_content %>